version: '3.8'

configs:
  turnserver_conf:
    file: ./turnserver.conf

services:
  entrypoint:
    image: ${IMAGE_PROJECT}/entrypoint:latest
    expose:
      - 5000
    networks:
      - local
      - server
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  client:
    image: ${IMAGE_PROJECT}/client:latest
    networks:
      - local
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  server:
    image: ${IMAGE_PROJECT}/server:latest
    networks:
      - local
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  coturn:
    image: coturn/coturn:alpine
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "32769-65535:32769-65535/udp"
    networks:
      - server
    configs:
      - source: turnserver_conf
        target: /etc/turnserver.conf
        mode: 0444
    command: ["-c", "/etc/turnserver.conf"]
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  local:
  server:
    external:
      name: server
