name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_PROJECT: ghcr.io/${{ github.repository }}

jobs:
  build-client:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: client
          push: true
          tags: ${{ env.IMAGE_PROJECT }}/client:latest

  build-server:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: ${{ env.IMAGE_PROJECT }}/server:latest

  build-entrypoint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push entrypoint
        uses: docker/build-push-action@v5
        with:
          context: entrypoint
          push: true
          tags: ${{ env.IMAGE_PROJECT }}/entrypoint:latest

  deploy:
    runs-on: ubuntu-22.04

    needs: [build-client, build-server, build-entrypoint]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy 🚀
        run: |
          env IMAGE_PROJECT="${{ env.IMAGE_PROJECT }}" \
            docker stack deploy --prune --with-registry-auth -c compose.yaml asmy-call
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
